version: '2'

services:
  wodbot:
    image: 'pmajewski/wodbot'
    build:
      context: .
    container_name: wodbot
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SQL_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SQL_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SQL_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
    ports:
      - '8080:8080'
      - '5005:5005'

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../db/data/sql/postgres/:/var/lib/postgresql/data
      - ../db/init/sql/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: 'redis:6.0'
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}

  mongo:
    image: "mongo:4.4.3"
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ../db/data/nosql/mongodb/:/data/db
#go with this https://www.linkedin.com/pulse/get-started-spring-boot-mongodb-docker-compose-saeid-farahi/